---
title: 'Exceptions : failwith (fonction)'
description: Découvrez comment la fonction « failwith » génère une F# exception.
ms.date: 05/16/2016
ms.openlocfilehash: 05d385ddfc98a910779a6f59949a7187c38f0812
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 04/23/2019
ms.locfileid: "61772682"
---
# <a name="exceptions-the-failwith-function"></a><span data-ttu-id="f0cb6-103">Exceptions : failwith (fonction)</span><span class="sxs-lookup"><span data-stu-id="f0cb6-103">Exceptions: The failwith Function</span></span>

<span data-ttu-id="f0cb6-104">Le `failwith` fonction génère une F# exception.</span><span class="sxs-lookup"><span data-stu-id="f0cb6-104">The `failwith` function generates an F# exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="f0cb6-105">Syntaxe</span><span class="sxs-lookup"><span data-stu-id="f0cb6-105">Syntax</span></span>

```fsharp
failwith error-message-string
```

## <a name="remarks"></a><span data-ttu-id="f0cb6-106">Notes</span><span class="sxs-lookup"><span data-stu-id="f0cb6-106">Remarks</span></span>

<span data-ttu-id="f0cb6-107">Le *chaîne du message d’erreur* dans la syntaxe précédente est une chaîne littérale ou une valeur de type `string`.</span><span class="sxs-lookup"><span data-stu-id="f0cb6-107">The *error-message-string* in the previous syntax is a literal string or a value of type `string`.</span></span> <span data-ttu-id="f0cb6-108">Il devient le `Message` propriété de l’exception.</span><span class="sxs-lookup"><span data-stu-id="f0cb6-108">It becomes the `Message` property of the exception.</span></span>

<span data-ttu-id="f0cb6-109">L’exception qui est générée par `failwith` est un `System.Exception` exception, ce qui est une référence qui porte le nom `Failure` dans F# code.</span><span class="sxs-lookup"><span data-stu-id="f0cb6-109">The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code.</span></span> <span data-ttu-id="f0cb6-110">Le code suivant illustre l’utilisation de `failwith` pour lever une exception.</span><span class="sxs-lookup"><span data-stu-id="f0cb6-110">The following code illustrates the use of `failwith` to throw an exception.</span></span>

[!code-fsharp[Main](../../../../samples/snippets/fsharp/lang-ref-2/snippet6001.fs)]

## <a name="see-also"></a><span data-ttu-id="f0cb6-111">Voir aussi</span><span class="sxs-lookup"><span data-stu-id="f0cb6-111">See also</span></span>

- [<span data-ttu-id="f0cb6-112">Gestion des exceptions</span><span class="sxs-lookup"><span data-stu-id="f0cb6-112">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="f0cb6-113">Types d'exceptions</span><span class="sxs-lookup"><span data-stu-id="f0cb6-113">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="f0cb6-114">Exceptions : Le `try...with` Expression</span><span class="sxs-lookup"><span data-stu-id="f0cb6-114">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="f0cb6-115">Exceptions : Le `try...finally` Expression</span><span class="sxs-lookup"><span data-stu-id="f0cb6-115">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="f0cb6-116">Exceptions : fonction `raise`</span><span class="sxs-lookup"><span data-stu-id="f0cb6-116">Exceptions: the `raise` Function</span></span>](the-raise-function.md)