---
title: Erreur du compilateur CS0156
ms.date: 07/20/2015
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
ms.openlocfilehash: f310b4b2b8aa320146d9114a999a82dcae2bb528
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 04/23/2019
ms.locfileid: "61687329"
---
# <a name="compiler-error-cs0156"></a>Erreur du compilateur CS0156
Une instruction throw sans argument n'est pas autorisée dans une clause finally qui est imbriquée dans la clause catch englobante la plus proche  
  
 Une instruction [throw](../../csharp/language-reference/keywords/throw.md) sans paramètre peut uniquement apparaître dans une clause **catch** qui n’accepte aucun paramètre.  
  
 Pour plus d’informations, consultez [Exception Handling Statements](../../csharp/language-reference/keywords/exception-handling-statements.md) et [Exceptions et gestion des exceptions](../../csharp/programming-guide/exceptions/index.md).  
  
 L’exemple suivant génère l’erreur CS0156 :  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
