---
ms.openlocfilehash: 94fad6fe910da6c528c5e13f529a6db274e07d5c
ms.sourcegitcommit: 0be8a279af6d8a43e03141e349d3efd5d35f8767
ms.translationtype: HT
ms.contentlocale: fr-FR
ms.lasthandoff: 04/18/2019
ms.locfileid: "59235350"
---
### <a name="change-in-behavior-for-taskwaitall-methods-with-time-out-arguments"></a><span data-ttu-id="a7a00-101">Changement de comportement des méthodes Task.WaitAll avec des arguments de délai d’attente</span><span class="sxs-lookup"><span data-stu-id="a7a00-101">Change in behavior for Task.WaitAll methods with time-out arguments</span></span>

|   |   |
|---|---|
|<span data-ttu-id="a7a00-102">Détails</span><span class="sxs-lookup"><span data-stu-id="a7a00-102">Details</span></span>|<span data-ttu-id="a7a00-103">Le comportement de <xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> est devenu plus cohérent dans .NET Framework 4.5. Dans .NET Framework 4, le comportement de ces méthodes n’était pas cohérent.</span><span class="sxs-lookup"><span data-stu-id="a7a00-103"><xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> behavior was made more consistent in .NET Framework 4.5.In the .NET Framework 4, these methods behaved inconsistently.</span></span> <span data-ttu-id="a7a00-104">Lorsque le délai d'attente expirait, si une ou plusieurs tâches étaient terminées ou annulées avant l'appel de la méthode, la méthode levait une exception <xref:System.AggregateException?displayProperty=name>.</span><span class="sxs-lookup"><span data-stu-id="a7a00-104">When the time-out expired, if one or more tasks were completed or canceled before the method call, the method threw an <xref:System.AggregateException?displayProperty=name> exception.</span></span> <span data-ttu-id="a7a00-105">Lorsque le délai d’attente expirait, si aucune tâche n’était terminée ou annulée avant l’appel de la méthode alors qu’une ou plusieurs tâches adoptaient ces états après l’appel de la méthode, la méthode retournait la valeur false.</span><span class="sxs-lookup"><span data-stu-id="a7a00-105">When the time-out expired, if no tasks were completed or canceled before the method call, but one or more tasks entered these states after the method call, the method returned false.</span></span><br/><br/><span data-ttu-id="a7a00-106">Dans .NET Framework 4.5, ces surcharges de méthode retournent désormais la valeur false si des tâches sont toujours en cours d’exécution quand l’intervalle de délai d’attente expire, et elles ne lèvent une exception <xref:System.AggregateException?displayProperty=name> que si une tâche d’entrée a été annulée (que cette annulation soit intervenue avant ou après l’appel de méthode) et qu’aucune autre tâche n’est en cours d’exécution.</span><span class="sxs-lookup"><span data-stu-id="a7a00-106">In the .NET Framework 4.5, these method overloads now return false if any tasks are still running when the time-out interval expired, and they throw an <xref:System.AggregateException?displayProperty=name> exception only if an input task was cancelled (regardless of whether it was before or after the method call) and no other tasks are still running.</span></span>|
|<span data-ttu-id="a7a00-107">Suggestion</span><span class="sxs-lookup"><span data-stu-id="a7a00-107">Suggestion</span></span>|<span data-ttu-id="a7a00-108">Si une exception <xref:System.AggregateException?displayProperty=name> a été interceptée dans le but de détecter une tâche ayant été annulée avant l’appel de <xref:System.Threading.Tasks.Task.WaitAll%2A>, ce code doit procéder à la même détection par le biais de la propriété <xref:System.Threading.Tasks.Task.IsCanceled%2A> (par exemple, .Any(t =&gt; t.IsCanceled)), puisque .NET Framework 4.6 lève une exception seulement si toutes les tâches attendues sont terminées avant le délai d’attente.</span><span class="sxs-lookup"><span data-stu-id="a7a00-108">If an <xref:System.AggregateException?displayProperty=name> was being caught as a means of detecting a task that was cancelled prior to the <xref:System.Threading.Tasks.Task.WaitAll%2A> call being invoked, that code should instead do the same detection via the  <xref:System.Threading.Tasks.Task.IsCanceled%2A> property (for example: .Any(t =&gt; t.IsCanceled)) since .NET Framework 4.6 will only throw in that case if all awaited tasks are completed prior to the timeout.</span></span>|
|<span data-ttu-id="a7a00-109">Portée</span><span class="sxs-lookup"><span data-stu-id="a7a00-109">Scope</span></span>|<span data-ttu-id="a7a00-110">Mineur</span><span class="sxs-lookup"><span data-stu-id="a7a00-110">Minor</span></span>|
|<span data-ttu-id="a7a00-111">Version</span><span class="sxs-lookup"><span data-stu-id="a7a00-111">Version</span></span>|<span data-ttu-id="a7a00-112">4.5</span><span class="sxs-lookup"><span data-stu-id="a7a00-112">4.5</span></span>|
|<span data-ttu-id="a7a00-113">Type</span><span class="sxs-lookup"><span data-stu-id="a7a00-113">Type</span></span>|<span data-ttu-id="a7a00-114">Runtime</span><span class="sxs-lookup"><span data-stu-id="a7a00-114">Runtime</span></span>|
|<span data-ttu-id="a7a00-115">API affectées</span><span class="sxs-lookup"><span data-stu-id="a7a00-115">Affected APIs</span></span>|<ul><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32,System.Threading.CancellationToken)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.TimeSpan)?displayProperty=nameWithType></li></ul>|
